POST http://localhost:8000/api/users/register
Content-Type: application/json

{
    "name": "test",
    "email": "test@mail.com",
    "password": "password"
}

###
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
    "email": "toms@mail.com",
    "password": "password"
}

###
GET http://localhost:8000/api/users/current

###
PATCH http://localhost:8000/api/users/current
Content-Type: application/json

{
    "email": "toms@mail.com",
    "password": "password2"
}

###
DELETE http://localhost:8000/api/users/logout
Authorization: Bearer 8b8be598-9902-492b-bec7-3648929c672e